name: "\U0001F41E Bug Report"
description: Report an issue with Eyecons

title: 'Bug: (fill in)'
labels:
  - bug

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what constitutes an error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know? Specify your VS Code version and operating system.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/azat-io/eyecons/issues) that reports the same bug to avoid creating a duplicate.
          required: true
