name: "\U0001F3A8 Theme Request"
description: Propose a new theme support to be added to the Eyecons

title: 'Theme Request: (fill in)'
labels:
  - feature

body:
  - type: textarea
    id: theme-description
    attributes:
      label: Describe the theme
      description: Specify the name of the theme. Provide a link to the theme repository.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional comments
      description: Is there anything else that's important to know?

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/azat-io/eyecons/issues) that reports the same feature to avoid creating a duplicate.
          required: true
