name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: block
          allowed-endpoints: >
            6abe5a43-4668-4f72-b3f7-823e2d8bbbbf.netlify.app:443
            api.github.com:443 api.netlify.com:443 api.netlifysdk.com:443
            dl.deno.land:443 edge.netlify.com:443 github.com:443
            registry.npmjs.org:443 release-assets.githubusercontent.com:443
            storage.googleapis.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Tools
        uses: ./.github/actions/install-tools

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Deploy to Netlify
        run: pnpm run docs:deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        shell: bash
